version: '2'

services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    environment: 
      MYSQL_ROOT_PASSWORD: admin234*
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    network_mode: bridge
    restart: "no"